name: "Release dev container features"
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Publish Features"
        run: devcontainer features publish -n ${{ github.repository }} src/chrome-deps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
